# Generated by Django 3.0.6 on 2020-05-19 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
