# Generated by Django 3.0.6 on 2020-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0002_auto_20200519_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='post_type',
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='boast',
            field=models.BooleanField(default=False),
        ),
    ]
