# Generated by Django 3.0.6 on 2020-06-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0003_auto_20200519_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='roast',
            field=models.BooleanField(default=True),
        ),
    ]
