# Generated by Django 3.0.6 on 2020-06-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0004_ghostpost_roast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='roast',
            field=models.BooleanField(default=False),
        ),
    ]
