# Generated by Django 3.0.6 on 2020-06-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0005_auto_20200625_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='roast',
        ),
    ]
